apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  annotations:
    {{- range $k, $v := .Values.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: default-http-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
