---
# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
controller:
  installPlugins:
    - kubernetes:latest
    - workflow:latest-aggregator
    - git:latest
    - github:latest
    - generic:latest-webhook-trigger
    - credential:latest-binding
    - google:latest-oauth-plugin
    - docker:latest-workflow
    - configuration:latest-as-code
    - slack:latest
    - mask:latest-passwords
    - timestamper:latest
  
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: "gce"
    # Replace with an actual hostname
    hostName: "jenkins-lab.local"
    annotation:
      kubernetes.io/ingress.global-static-ip-name: "gke-jenkins-ip"
      kubernetes.io/ingress.allow-http: "true"
    # Add cert manager from ManagedCertificates
    tls: []

  serviceType: ClusterIP

  serviceAccount:
    create: false
    name: jenkins-deployer

  JCasC:
    defaultConfig: false
    configScripts: 
      basic: |
        jenkins:
          authorizationStrategy: loggedInUsersCanDoAnything
          securityRealm: |-
          local:
            allowsSignup: false
            enableCaptcha: false
            users:
            - id: "admin"
              name: "Jenkins Admin"
              password: "admin"
        unclassified:
          location:
            url: "http://{{ .Values.controller.ingress.hostName }}/"

# Agent setup 
agent:
  podTemplates:

  #  python: |
  #    - name: python
  #      label: jenkins-python
  #      serviceAccount: jenkins
  #      containers:
  #        - name: python
  #          image: python:3
  #          command: "/bin/sh -c"
  #          args: "cat"
  #          ttyEnabled: true
  #          privileged: true
  #          resourceRequestCpu: "400m"
  #          resourceRequestMemory: "512Mi"
  #          resourceLimitCpu: "1"
  #          resourceLimitMemory: "1024Mi"